apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    app: frontend
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      project: expense
  template:
    metadata:
      labels:
        app: frontend
        project: expense
    spec:
      containers:
      - name: nginx
        image: vot5kor/frontend:1.2.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector:  # labels are used to selectors
      app: frontend
      project: expense
  ports:
    - protocol: TCP
      port: 80      # The port exposed by the Service
      targetPort: 8080  #target container port