apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      project: expense
  template:
    metadata:
      labels:
        app: backend
        project: expense
    spec:
      containers:
      - name: nginx
        image: vot5kor/backend:1.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:  # labels are used to selectors
      app: backend
      project: expense
  ports:
    - protocol: TCP
      port: 8080        # The port exposed by the Service
      targetPort: 8080  #target container port