apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels:
    app: mysql
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
    app: mysql
    project: expense
  template:
    metadata:
      labels:
        app: mysql
        project: expense
    spec:
      containers:
      - name: nginx
        image: vot5kor/mysql:1.0.0
