apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels:
    app: mysql
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      project: expense
  template:
    metadata:
      labels:
        app: mysql
        project: expense
    spec:
      containers:
      - name: nginx
        image: vot5kor/mysql:1.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: mysql 
spec:
  selector:  # labels are used to selectors
      app: mysql
      project: expense
  ports:
    - protocol: TCP
      port: 3306        # The port exposed by the Service
      targetPort: 3306  #target container port